import json
import os

def generate_restaurants():
    """
    Generates 10 static restaurants (5 for owner 1 in Karşıyaka, 5 for owner 2 in Bornova)
    with working hours set to 00:00–23:59, and two randomly chosen (ID 3 & 7) with 00:00–00:01.
    """
    restaurants = [
        # Owner 1 (Karşıyaka)
        {
            "id": 1,
            "owner_id": 1,
            "restaurantName": "Bostanlı Lezzet",
            "restaurantDescription": "Geleneksel tatlarla modern dokunuşlar",
            "restaurantEmail": "info@bostanlilezzet.com",
            "restaurantPhone": "+905312300001",
            "longitude": 27.140000,
            "latitude": 38.455000,
            "category": "Baked Goods",
            "workingDays": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "23:59",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F1.jpg?alt=media&token=19be3e53-e836-4f26-9411-0559fdf49ce1",
            "pickup": True,
            "delivery": True,
            "maxDeliveryDistance": 5.0,
            "deliveryFee": 8.0,
            "minOrderAmount": 20.0,
            "flash_deals_available": False,
            "flash_deals_count": 0
        },
        {
            "id": 2,
            "owner_id": 1,
            "restaurantName": "Mavişehir Café",
            "restaurantDescription": "Şehir manzaralı kahvaltı ve atıştırmalıklar",
            "restaurantEmail": "hello@mavisehircafe.com",
            "restaurantPhone": "+905312300002",
            "longitude": 27.032000,
            "latitude": 38.453000,
            "category": "Fruits & Vegetables",
            "workingDays": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "23:59",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F2.jpg?alt=media&token=105e0eec-5af0-4767-9a2e-93e5e907db24",
            "pickup": True,
            "delivery": False,
            "maxDeliveryDistance": None,
            "deliveryFee": None,
            "minOrderAmount": 0.0,
            "flash_deals_available": False,
            "flash_deals_count": 0
        },
        {
            "id": 3,
            "owner_id": 1,
            "restaurantName": "Alaybey Ocakbaşı",
            "restaurantDescription": "Ege usulü kebap ve mezeler",
            "restaurantEmail": "contact@alaybeyocakbasi.com",
            "restaurantPhone": "+905312300003",
            "longitude": 27.166000,
            "latitude": 38.458000,
            "category": "Meat & Seafood",
            "workingDays": "Tuesday,Wednesday,Thursday,Friday,Saturday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "00:01",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F3.jpg?alt=media&token=8c24506b-c453-4836-a630-22c4ef1df215",
            "pickup": True,
            "delivery": True,
            "maxDeliveryDistance": 4.0,
            "deliveryFee": 10.0,
            "minOrderAmount": 25.0,
            "flash_deals_available": True,
            "flash_deals_count": 1
        },
        {
            "id": 4,
            "owner_id": 1,
            "restaurantName": "Donanmacı Dürüm",
            "restaurantDescription": "Pratik dürüm çeşitleri ve içecekler",
            "restaurantEmail": "info@donanmacidurumm.com",
            "restaurantPhone": "+905312300004",
            "longitude": 27.172000,
            "latitude": 38.434000,
            "category": "Dairy Products",
            "workingDays": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "23:59",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F4.jpg?alt=media&token=580c03f8-d5ac-4c8d-a1d0-3951e51822a5",
            "pickup": True,
            "delivery": True,
            "maxDeliveryDistance": 6.0,
            "deliveryFee": 7.0,
            "minOrderAmount": 15.0,
            "flash_deals_available": True,
            "flash_deals_count": 2
        },
        {
            "id": 5,
            "owner_id": 1,
            "restaurantName": "Tuna Balık Evi",
            "restaurantDescription": "Taze balık çeşitleri ve deniz ürünleri",
            "restaurantEmail": "reservations@tunabalikevi.com",
            "restaurantPhone": "+905312300005",
            "longitude": 27.160000,
            "latitude": 38.428000,
            "category": "Ready Meals",
            "workingDays": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "23:59",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F5.jpg?alt=media&token=22dcbdb5-5440-4ac2-b7c5-7dc4ca06a76e",
            "pickup": False,
            "delivery": True,
            "maxDeliveryDistance": 5.0,
            "deliveryFee": 12.0,
            "minOrderAmount": 40.0,
            "flash_deals_available": False,
            "flash_deals_count": 0
        },

        # Owner 2 (Bornova)
        {
            "id": 6,
            "owner_id": 2,
            "restaurantName": "Evka 3 Lezzet Durağı",
            "restaurantDescription": "Öğle ve akşam öğünlerinde ev yemeği tadı",
            "restaurantEmail": "info@evka3lezzet.com",
            "restaurantPhone": "+905376300001",
            "longitude": 27.212000,
            "latitude": 38.441000,
            "category": "Snacks",
            "workingDays": "Monday,Tuesday,Wednesday,Thursday,Friday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "23:59",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F6.jpg?alt=media&token=f92b831f-dbac-44e7-98e3-728edf63c7c3",
            "pickup": True,
            "delivery": True,
            "maxDeliveryDistance": 5.0,
            "deliveryFee": 6.0,
            "minOrderAmount": 20.0,
            "flash_deals_available": False,
            "flash_deals_count": 0
        },
        {
            "id": 7,
            "owner_id": 2,
            "restaurantName": "Bornova Pidecisi",
            "restaurantDescription": "Çeşit çeşit pideler, lahmacun ve ızgaralar",
            "restaurantEmail": "contact@bornovapide.com",
            "restaurantPhone": "+905376300002",
            "longitude": 27.208000,
            "latitude": 38.436000,
            "category": "Beverages",
            "workingDays": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "00:01",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F7.jpg?alt=media&token=fa2c8f95-9371-44eb-b79d-90a7de6123b9",
            "pickup": True,
            "delivery": False,
            "maxDeliveryDistance": None,
            "deliveryFee": None,
            "minOrderAmount": 0.0,
            "flash_deals_available": True,
            "flash_deals_count": 1
        },
        {
            "id": 8,
            "owner_id": 2,
            "restaurantName": "1071 Kebap & Lahmacun",
            "restaurantDescription": "Anadolu ezgileriyle saf lezzet",
            "restaurantEmail": "info@1071kebap.com",
            "restaurantPhone": "+905376300003",
            "longitude": 27.180000,
            "latitude": 38.446500,
            "category": "Pantry Items",
            "workingDays": "Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "23:59",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F8.jpg?alt=media&token=8b92ce70-7e86-48e3-b243-e15de2217683",
            "pickup": False,
            "delivery": True,
            "maxDeliveryDistance": 4.5,
            "deliveryFee": 9.0,
            "minOrderAmount": 25.0,
            "flash_deals_available": False,
            "flash_deals_count": 0
        },
        {
            "id": 9,
            "owner_id": 2,
            "restaurantName": "Bornova Sushi Bar",
            "restaurantDescription": "Japon mutfağının taze seçenekleri",
            "restaurantEmail": "hello@bornovasushi.com",
            "restaurantPhone": "+905376300004",
            "longitude": 27.190000,
            "latitude": 38.438000,
            "category": "Frozen Foods",
            "workingDays": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "23:59",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F9.jpg?alt=media&token=bbb8e8c0-3062-4153-a6f5-e220b6ac7c29",
            "pickup": True,
            "delivery": True,
            "maxDeliveryDistance": 3.5,
            "deliveryFee": 10.0,
            "minOrderAmount": 30.0,
            "flash_deals_available": True,
            "flash_deals_count": 2
        },
        {
            "id": 10,
            "owner_id": 2,
            "restaurantName": "Bornova Vegan Mutfağı",
            "restaurantDescription": "Bitkisel bazlı sağlıklı lezzetler",
            "restaurantEmail": "info@bornovavegan.com",
            "restaurantPhone": "+905376300005",
            "longitude": 27.205000,
            "latitude": 38.420000,
            "category": "Organic Products",
            "workingDays": "Monday,Tuesday,Wednesday,Thursday,Friday",
            "workingHoursStart": "00:00",
            "workingHoursEnd": "23:59",
            "listings": 4,
            "rating": None,
            "ratingCount": 0,
            "image_url": "https://firebasestorage.googleapis.com/v0/b/freshdeal-d691b.firebasestorage.app/o/restaurants%2F10.jpg?alt=media&token=09ffe92a-2937-4908-aacf-f78176f3a6b0",
            "pickup": True,
            "delivery": False,
            "maxDeliveryDistance": None,
            "deliveryFee": None,
            "minOrderAmount": 0.0,
            "flash_deals_available": False,
            "flash_deals_count": 0
        }
    ]

    # Set all restaurants to have a rating and ratingCount
    for r in restaurants:
        r["rating"] = 4.5  # or any float value you want
        r["ratingCount"] = 100  # or any int value you want

    os.makedirs('../exported_json', exist_ok=True)
    with open('../exported_json/restaurants.json', 'w', encoding='utf-8') as f:
        json.dump(restaurants, f, ensure_ascii=False, indent=2)

    print(f"Saved {len(restaurants)} restaurants to ../exported_json/restaurants.json")

if __name__ == "__main__":
    generate_restaurants()
